upstream php_fpm { server atom-app:9000; }

server {
    listen 80 default_server;
    root /usr/share/nginx/atom;

    index index.php;
    charset utf-8;

    location / {
        try_files $uri /index.php?$args;
    }

    location ~ \.php$ {
        include       fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass  php_fpm;
    }

    # deny access to hidden files
    location ~ /\.(?!well-known) { deny all; }
}
