# docker-compose.override.yml
services:
  atom-app:
    build:
      context: .
      dockerfile: ./init/Dockerfile
      args:
        ATOM_VERSION: ${ATOM_VERSION}
    volumes:
      - atom_app:/usr/share/nginx/atom
      - ./plugins/arLettresPlugin:/host-plugins/arLettresPlugin:ro
    environment:
      - APP_ENV=dev
    networks:
      - atom-net

  atom-nginx:
    image: nginx:1.27-alpine
    depends_on:
      - atom-app
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - atom_app:/usr/share/nginx/atom:ro
      - ./init/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - atom-net

volumes:
  atom_app:

networks:
  atom-net:
