# docker-compose.prod.yml
services:
  atom-app:
    image: unillett/atom:${ATOM_VERSION}
    restart: unless-stopped
    volumes:
      - uploads_data:/usr/share/nginx/atom/uploads
      - log_data:/usr/share/nginx/atom/log
      - cache_data:/usr/share/nginx/atom/cache

  atom-mysql:
    restart: unless-stopped
  atom-elasticsearch:
    restart: unless-stopped
  atom-gearman:
    restart: unless-stopped

volumes:
  uploads_data:
  log_data:
  cache_data:
